/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new session */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List upcoming sessions */
        get: operations["listUpcomingSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join an existing session */
        post: operations["joinSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bibles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available translations */
        get: operations["listBibles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bible-books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List normalized bible book metadata */
        get: operations["listBibleBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/passage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a passage by reference and translation */
        get: operations["getPassage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error?: string;
            details?: {
                [key: string]: unknown;
            };
        };
        SessionCreated: {
            /** Format: uuid */
            id: string;
            shortCode: string;
            controllerJoinToken: string;
            displayJoinToken: string;
            /** Format: date-time */
            createdAt: string;
            name: string;
            /** Format: date-time */
            scheduledAt?: string | null;
        };
        CreateSessionRequest: {
            name?: string;
            /** Format: date-time */
            scheduledAt?: string | null;
        };
        JoinRequest: {
            /** @enum {string} */
            role: "controller" | "display";
            joinToken: string;
        };
        JoinResult: {
            ok: boolean;
            controllerLocked: boolean;
            message?: string;
            /** Format: uuid */
            sessionId: string;
            shortCode: string;
            /** @enum {string} */
            role: "controller" | "display";
            name: string;
            /** Format: date-time */
            scheduledAt?: string | null;
        };
        UpcomingSession: {
            /** Format: uuid */
            id: string;
            name: string;
            shortCode: string;
            controllerJoinToken: string;
            displayJoinToken: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            scheduledAt?: string | null;
        };
        Bible: {
            /** @example RVR1960 */
            code: string;
            /** @example Reina-Valera 1960 */
            name: string;
            /** @example es */
            language: string;
            /** @example external:RVR1960Provider */
            provider: string;
            /** @example no-store */
            cachePolicy?: string;
            license?: string;
            version?: string;
            /** @description true when the translation is bundled locally and works without network access */
            isOfflineReady?: boolean;
        };
        BibleBookMetadata: {
            id: string;
            englishDisplayName: string;
            spanishDisplayName: string;
            slug: string;
            ordinal?: number | null;
            aliases: string[];
        };
        PassageResult: {
            /** @example Juan 3:16-18 */
            reference: string;
            /** @example RVR1960 */
            translation: string;
            verses: components["schemas"]["Verse"][];
            attribution?: components["schemas"]["Attribution"];
            /** @example no-store */
            cachePolicy?: string;
        };
        Verse: {
            /** @example Juan */
            book: string;
            /** @example 3 */
            chapter: number;
            /** @example 16 */
            verse: number;
            text: string;
        };
        Attribution: {
            required: boolean;
            text?: string;
            url?: string;
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreated"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listUpcomingSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upcoming sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpcomingSession"][];
                };
            };
        };
    };
    joinSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRequest"];
            };
        };
        responses: {
            /** @description Joined session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinResult"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Controller already locked */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinResult"];
                };
            };
        };
    };
    listBibles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bible"][];
                };
            };
        };
    };
    listBibleBooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleBookMetadata"][];
                };
            };
        };
    };
    getPassage: {
        parameters: {
            query: {
                /** @description Scripture reference (e.g., 'Jn 3:16-18') */
                ref: string;
                /** @description Translation code (e.g., 'RVR1960', 'NTV') */
                translation: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Passage result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PassageResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
}
