// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wtrfll.Server.Slices.Sessions.Domain;
using Wtrfll.Server.Infrastructure.Data;

#nullable disable

namespace Wtrfll.Server.Infrastructure.Data.Migrations;

[DbContext(typeof(AppDbContext))]
public partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

        modelBuilder.Entity("Wtrfll.Server.Slices.Sessions.Domain.Session", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("TEXT");

            b.Property<string>("ControllerJoinCode")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("TEXT");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("TEXT");

            b.Property<string>("DisplayJoinCode")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("TEXT");

            b.Property<string>("ShortCode")
                .IsRequired()
                .HasMaxLength(12)
                .HasColumnType("TEXT");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("ShortCode")
                .IsUnique();

            b.ToTable("Sessions");
        });

        modelBuilder.Entity("Wtrfll.Server.Slices.Sessions.Domain.SessionParticipant", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("TEXT");

            b.Property<DateTime>("JoinedAt")
                .HasColumnType("TEXT");

            b.Property<string>("Role")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("TEXT");

            b.Property<Guid>("SessionId")
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("SessionId");

            b.HasIndex("SessionId", "Role");

            b.ToTable("SessionParticipants");
        });

        modelBuilder.Entity("Wtrfll.Server.Slices.Sessions.Domain.SessionParticipant", b =>
        {
            b.HasOne("Wtrfll.Server.Slices.Sessions.Domain.Session", "Session")
                .WithMany("Participants")
                .HasForeignKey("SessionId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Session");
        });

        modelBuilder.Entity("Wtrfll.Server.Slices.Sessions.Domain.Session", b =>
        {
            b.Navigation("Participants");
        });
#pragma warning restore 612, 618
    }
}

